name: Precommit - Unit Tests
on: [pull_request]
jobs:
  build:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
    - name: clean disk
      run: |
        sudo swapoff -a
        sudo rm -rf /swapfile /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo apt clean
        docker rmi $(docker images -q) -f
        df -h

      env:
        CLOUDSMITH_USERNAME: ${{ secrets.CLOUDSMITH_USERNAME }}
        CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up yq
      run: |
        sudo wget https://github.com/mikefarah/yq/releases/download/v4.6.0/yq_linux_amd64 -O /usr/bin/yq
        sudo chmod +x /usr/bin/yq
        yq --help

      env:
        CLOUDSMITH_USERNAME: ${{ secrets.CLOUDSMITH_USERNAME }}
        CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    - name: Login to GitHub Packages Docker Registry
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ secrets.IMAGE_GITHUB_USERNAME }}
        password: ${{ secrets.IMAGE_GITHUB_TOKEN }}

    - name: Auto generate crd model
      run: ./scripts/generate-crd.sh

      env:
        CLOUDSMITH_USERNAME: ${{ secrets.CLOUDSMITH_USERNAME }}
        CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    - name: Format license
      run: mvn license:format

      env:
        CLOUDSMITH_USERNAME: ${{ secrets.CLOUDSMITH_USERNAME }}
        CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    - name: Run mesh worker service unit test
      run: mvn clean install
      env:
        CLOUDSMITH_USERNAME: ${{ secrets.CLOUDSMITH_USERNAME }}
        CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
